[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = [
  "apt-get update -qq",
  "apt-get install -y -qq ffmpeg",
  "pip install -r requirements.txt"
]

[start]
cmd = "python bot.py"
